name: Release App

on:
  push:
    tags:
      - 'v*' # Trigger on version tags (e.g. v1.0.0)

jobs:
  release:
    runs-on: windows-latest
    permissions:
      contents: write # Needed for creating Releases

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Install Dependencies
        run: npm install

      - name: Build and Publish
        run: npm run release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Needed for publishing to GitHub Releases
